package de.gaz.eedu.course.classroom.model;

import de.gaz.eedu.entity.model.EntityModel;
import lombok.NonNull;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

public record ClassRoomModel(
        @NonNull String id,
        @NonNull Long[] students,
        @Nullable Long tutor
) implements EntityModel<String>
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ClassRoomModel{" +
                "id='" + id + '\'' +
                ", students=" + Arrays.toString(students) +
                ", tutor=" + tutor +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        ClassRoomModel that = (ClassRoomModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
